version: '3'
services:
  api:
    build: .
    depends_on:
      - mymongo
    environment:
      - MONGODB_URL=mongodb://admin:admin@mymongo:27017
      - LOGLEVEL=DEBUG
    ports:
      - 8000:8000
    volumes:
      - ./:/app
  mymongo:
    image: mongo:4.2.3-bionic
    container_name: mymongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=arch
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      # seeding scripts
      - ./mongo-entrypoint:/docker-entrypoint-initdb.d
      # named volumes
      - mongodb:/data/db
      - mongoconfig:/data/configdb
volumes:
  # default dir on Ubuntu: /var/lib/docker/volumes
  mongodb:
  mongoconfig:
