version: '3'
services:
  api:
    build: .
    environment:
      - LOG_LEVEL=DEBUG
      - DB_URL=sqlite:///./sql_app.db
      - JWT_SECRET=secret
    ports:
      - 8000:8000
    volumes:
      - ./:/app
